import React from "react";
import {
  diffDatesByDay,
  capitalize,
  diffArrays,
  diffArraysWithId,
  generateRandomNumber,
  capitalizeFirstLetter,
  capitalizeAllStartingWords,
  isBlankString,
  generateRandomString,
  generateRandomHexColor,
  generateRandomBoolean,
  coinflip,
  isEven,
  removeAllDuplicates,
  isArray,
  mergeArrays,
  isNotEmptyArray,
  safelyParseJson,
  isEmptyObj,
  shuffleArray,
  convertSnakeToCamelCase,
  convertRGBToHexColor,
  getMinMaxOfArray,
  sleep,
  toObj,
  getUnion,
  partition,
} from "../../../../lib/lulin";
// Add react-live imports you need here
const ReactLiveScope = {
  React,
  ...React,
  diffDatesByDay,
  capitalize,
  diffArrays,
  diffArraysWithId,
  generateRandomNumber,
  capitalizeFirstLetter,
  capitalizeAllStartingWords,
  isBlankString,
  generateRandomString,
  generateRandomHexColor,
  generateRandomBoolean,
  coinflip,
  isEven,
  removeAllDuplicates,
  isArray,
  mergeArrays,
  isNotEmptyArray,
  safelyParseJson,
  isEmptyObj,
  shuffleArray,
  convertSnakeToCamelCase,
  convertRGBToHexColor,
  getMinMaxOfArray,
  sleep,
  toObj,
  getUnion,
  partition,
};
export default ReactLiveScope;
